
version: 2

models:
  - name: account
    columns:
      - name: id
        tests:
          - unique
          - not_null
  - name: opportunity
    columns:
      - name: id
        tests:
          - unique
          - not_null
  - name: opportunity_line_item
    columns:
      - name: id
        tests:
          - unique
          - not_null




